#!/usr/bin/env python
# coding: utf-8

# git-issue, version 0.3
#
# by John Wiegley <johnw@newartisans.com>

# TODO: (until I can add these bugs to the repo itself!)
#
# 1. use utf-8 throughout
# 2. use -z flag for ls-tree
# 3. use UTC throughout

import sys
import os
import re
import string
import optparse

try:
    from cStringIO import StringIO
except:
    from StringIO import StringIO

import cPickle
import xml.dom.minidom

from datetime   import datetime
from subprocess import Popen, PIPE
from os.path    import isdir, isfile, join

######################################################################

iso_fmt       = "%Y%m%dT%H%M%S"
options       = None
cache_version = 9

######################################################################

class Person:
    def __init__(self, name, email):
        self.name  = name
        self.email = email

    def __str__(self):
        return "%s <%s>" % (self.name, self.email)

    def from_xml(cls, node):
        person = Person(node.childNodes[0].data,
                        node.childNodes[1].data)
        return person

    from_xml = classmethod(from_xml)

def to_xml(doc, parent, data):
    if isinstance(data, datetime):
        element = doc.createElement("datetime")
        element.appendChild(doc.createTextNode(data.strftime(iso_fmt)))
        parent.appendChild(element)

    elif isinstance(data, Person):
        person = doc.createElement("person")

        name = doc.createElement("name")
        name.appendChild(doc.createTextNode(data.name))
        person.appendChild(name)

        email = doc.createElement("email")
        email.appendChild(doc.createTextNode(data.email))
        person.appendChild(email)

        parent.appendChild(person)

    elif isinstance(data, list):
        element = doc.createElement("list")
        for child in data:
            to_xml(doc, element, child)
        parent.appendChild(element)

    elif isinstance(data, str):
        parent.appendChild(doc.createTextNode(data))

    else:
        assert False

class Issue:
    def __init__(self, issueSet, author, title,
                 summary     = None,
                 description = None,
                 reporters   = [],
                 owners      = [],
                 assigned    = None,
                 carbons     = [],
                 status      = "new",
                 resolution  = None,
                 issue_type  = "defect",
                 components  = [],
                 version     = None,
                 milestone   = None,
                 severity    = "major",
                 priority    = "medium",
                 tags        = []):
        self.issueSet    = issueSet
        self.name        = None
        self.author      = author
        self.title       = title
        self.summary     = summary
        self.description = description
        self.reporters   = reporters
        self.owners      = owners
        self.assigned    = assigned
        self.carbons     = carbons
        self.status      = status
        self.resolution  = resolution
        self.issue_type  = issue_type
        self.components  = components
        self.version     = version
        self.milestone   = milestone
        self.severity    = severity
        self.priority    = priority
        self.tags        = tags
        self.created     = datetime.now()
        self.modified    = None
        self.changes     = {}
        self.dirty       = True

    def mark_dirty(self):
        self.modified       = datetime.now()
        self.dirty          = True
        self.issueSet.dirty = True

    def note_change(self, field, before, after):
        if self.changes.has_key(field):
            data = self.changes[field]
            data[1] = after
        else:
            data = [before, after]
        self.changes[field] = data

    def dump_changes(self, include_header = True, fd = sys.stdout):
        if not self.changes:
            return
            
        doc = xml.dom.minidom.Document()
        changes = doc.createElement("changes")
        doc.appendChild(changes)

        for field_name in self.changes.keys():
            field = doc.createElement("field")
            field.setAttribute("name", field_name)

            data = self.changes[field_name]

            before = doc.createElement("before")
            to_xml(doc, before, data[0])
            field.appendChild(before)

            after = doc.createElement("after")
            to_xml(doc, after, data[1])
            field.appendChild(after)

            changes.appendChild(field)

        if include_header:
            fd.write(doc.toprettyxml(indent = "", encoding = "utf-8"))
        else:
            buffer = StringIO()
            buffer.write(doc.toprettyxml(indent = "", encoding = "utf-8"))
            fd.write(re.sub('^.+\n', '', buffer.getvalue()))

        doc.unlink()

    def set_author(self, author):
        self.note_change('author', self.author, author)
        self.author = author

    def set_title(self, title):
        self.note_change('title', self.title, title)
        self.title = title

    def set_summary(self, summary):
        self.note_change('summary', self.summary, summary)
        self.summary = summary

    def set_description(self, description):
        self.note_change('description', self.description, description)
        self.description = description

    def set_reporters(self, reporters):
        self.note_change('reporters', self.reporters, reporters)
        self.reporters = reporters

    def set_owners(self, owners):
        self.note_change('owners', self.owners, owners)
        self.owners = owners

    def set_assigned(self, assigned):
        self.note_change('assigned', self.assigned, assigned)
        self.assigned = assigned

    def set_carbons(self, carbons):
        self.note_change('carbons', self.carbons, carbons)
        self.carbons = carbons

    def set_status(self, status):
        self.note_change('status', self.status, status)
        self.status = status

    def set_resolution(self, resolution):
        self.note_change('resolution', self.resolution, resolution)
        self.resolution = resolution

    def set_issue_type(self, issue_type):
        self.note_change('type', self.issue_type, issue_type)
        self.issue_type = issue_type

    def set_components(self, components):
        self.note_change('components', self.components, components)
        self.components = components

    def set_version(self, version):
        self.note_change('version', self.version, version)
        self.version = version

    def set_milestone(self, milestone):
        self.note_change('milestone', self.milestone, milestone)
        self.milestone = milestone

    def set_severity(self, severity):
        self.note_change('severity', self.severity, severity)
        self.severity = severity

    def set_priority(self, priority):
        self.note_change('priority', self.priority, priority)
        self.priority = priority

    def set_tags(self, tags):
        self.note_change('tags', self.tags, tags)
        self.tags = tags

    def format_long_text(self, text, indent = 13):
        if not text:
            return "<none>"

        lines = string.split(text, '\n')
        
        buffer = StringIO()
        first = True
        for line in lines:
            if not first:
                buffer.write("\n%s" % (" " * indent))
            else:
                first = False
            buffer.write(line)

        return buffer.getvalue()

    def format_people_list(self, people, indent = 13):
        if not people:
            return "<no one yet>"

        buffer = StringIO()
        first = True
        for person in people:
            if not first:
                buffer.write(",\n%s" % (" " * indent))
            else:
                first = False
            buffer.write(person)

        return buffer.getvalue()

    def from_xml(cls, issueSet, doc):
        node   = doc.firstChild
        name   = node.childNodes[0].data
        author = Person.from_xml(node.childNodes[1])
        title  = node.childNodes[2].data

        issue  = Issue(issueSet, author, title)
        issue.name  = name
        issue.dirty = False
        return issue

    from_xml = classmethod(from_xml)

    def dump_xml(self, fd = sys.stdout):
        import xml.dom.minidom

        doc = xml.dom.minidom.Document()
        issue = doc.createElement("issue")
        doc.appendChild(issue)

        if self.name:
            name = doc.createElement("name")
            to_xml(doc, name, self.name)
            issue.appendChild(name)

        author = doc.createElement("author")
        to_xml(doc, author, self.author)
        issue.appendChild(author)

        title = doc.createElement("title")
        to_xml(doc, title, self.title)
        issue.appendChild(title)

        if self.summary:
            summary = doc.createElement("summary")
            to_xml(doc, summary, self.summary)
            issue.appendChild(summary)

        if self.description:
            description = doc.createElement("description")
            to_xml(doc, description, self.description)
            issue.appendChild(description)

        if self.reporters:
            reporters = doc.createElement("reporters")
            to_xml(doc, reporters, self.reporters)
            issue.appendChild(reporters)

        if self.owners:
            owners = doc.createElement("owners")
            to_xml(doc, owners, self.owners)
            issue.appendChild(owners)

        if self.assigned:
            assigned = doc.createElement("assigned")
            to_xml(doc, assigned, self.assigned)
            issue.appendChild(assigned)

        if self.carbons:
            carbons = doc.createElement("carbons")
            to_xml(doc, carbons, self.carbons)
            issue.appendChild(carbons)

        if self.status:
            status = doc.createElement("status")
            to_xml(doc, status, self.status)
            issue.appendChild(status)

        if self.resolution:
            resolution = doc.createElement("resolution")
            to_xml(doc, resolution, self.resolution)
            issue.appendChild(resolution)

        if self.issue_type:
            issue_type = doc.createElement("type")
            to_xml(doc, issue_type, self.issue_type)
            issue.appendChild(issue_type)

        if self.components:
            components = doc.createElement("components")
            to_xml(doc, components, self.components)
            issue.appendChild(components)

        if self.version:
            version = doc.createElement("version")
            to_xml(doc, version, self.version)
            issue.appendChild(version)

        if self.milestone:
            milestone = doc.createElement("milestone")
            to_xml(doc, milestone, self.milestone)
            issue.appendChild(milestone)

        if self.severity:
            severity = doc.createElement("severity")
            to_xml(doc, severity, self.severity)
            issue.appendChild(severity)

        if self.priority:
            priority = doc.createElement("priority")
            to_xml(doc, priority, self.priority)
            issue.appendChild(priority)

        if self.tags:
            tags = doc.createElement("tags")
            to_xml(doc, tags, self.tags)
            issue.appendChild(tags)

        created = doc.createElement("created")
        to_xml(doc, created, self.created)
        issue.appendChild(created)

        if self.modified:
            modified = doc.createElement("modified")
            to_xml(doc, modified, self.modified)
            issue.appendChild(modified)

        fd.write(doc.toprettyxml(indent = "", encoding = "utf-8"))
        doc.unlink()

    def __getstate__(self):
        odict = self.__dict__.copy() # copy the dict since we change it
        del odict['changes']         # remove change log
        del odict['dirty']           # remove dirty flag
        return odict

    def __setstate__(self,dict):
        self.__dict__.update(dict)   # update attributes
        self.changes = {}
        self.dirty   = False

class IssueSet:
    """An IssueSet refers to a group of issues.  There is always at least one
    IssueSet that refers to all of the issues which exist in a repository.
    Other IssueSet's can be generated from that one as "views" or queries into
    that data.

    In essence, it contains both a set of Issue's which can be looked up by
    their unique identifier, and also certain global definition, like the
    allowable components, etc."""
    def __init__(self):
        self.statuses      = []
        self.resolutions   = []
        self.issue_types   = []
        self.components    = []
        self.versions      = []
        self.milestones    = []
        self.severities    = []
        self.priorities    = []
        self.issues        = {}
        self.issues_HEAD   = None
        self.dirty         = False
        self.cache_version = cache_version
        self.created       = datetime.now()

    def head(self):
        if not self.issues_HEAD:
            self.issues_HEAD = self.current_head()
        return self.issues_HEAD

    def update_head(self, new_head):
        self.issues_HEAD = new_head
        self.dirty       = True

    def current_head(self):
        assert False

    def current_author(self):
        assert False

    def read_project(self):
        pass

    def read_issues(self):
        assert False

    def add_issue(self, issue):
        self.issues[issue.name] = issue
        self.dirty = True

    def read_issue(self, name):
        assert False
    def write_issue(self, issue):
        assert False

    def issues_cache_file(self):
        assert False
    
    def dump_xml(self, fd = sys.stdout):
        import xml.dom.minidom

        doc = xml.dom.minidom.Document()
        set = doc.createElement("issue-set")
        doc.appendChild(set)

        created = doc.createElement("created")
        to_xml(doc, created, self.created)
        set.appendChild(created)

        if self.statuses:
            statuses = doc.createElement("statuses")
            to_xml(doc, statuses, self.statuses)
            set.appendChild(statuses)

        if self.resolutions:
            resolutions = doc.createElement("resolutions")
            to_xml(doc, resolutions, self.resolutions)
            set.appendChild(resolutions)

        if self.issue_types:
            issue_types = doc.createElement("types")
            to_xml(doc, issue_types, self.issue_types)
            set.appendChild(issue_types)

        if self.components:
            components = doc.createElement("components")
            to_xml(doc, components, self.components)
            set.appendChild(components)

        if self.versions:
            versions = doc.createElement("versions")
            to_xml(doc, versions, self.versions)
            set.appendChild(versions)

        if self.milestones:
            milestones = doc.createElement("milestones")
            to_xml(doc, milestones, self.milestones)
            set.appendChild(milestones)

        if self.severities:
            severities = doc.createElement("severities")
            to_xml(doc, severities, self.severities)
            set.appendChild(severities)

        if self.priorities:
            priorities = doc.createElement("priorities")
            to_xml(doc, priorities, self.priorities)
            set.appendChild(priorities)

        fd.write(doc.toprettyxml(indent = "", encoding = "utf-8"))
        doc.unlink()

    def load_state(cls, issueSet):
        """Given a newly created IssueSet object as a template, see if we can
        restore the cached version of the data from disk, and then check whether
        it's still valid.  This can _greatly_ speed up subsequent list and show
        operations.

        The reason why a newly created template exists is to abstract
        DVCS-specific behavior, such as the location of the cache file.

        Thus, a typical session looks like this:

          issueSet = GitIssueSet()   # or whichever DVCS backend you use

          if ... looking at issues list is required ...:
              issueSet = load_issues(issueSet)

              ... use the issue data ..."""
        cache_file = issueSet.issues_cache_file()
        if isfile(cache_file):
            fd = open(cache_file, 'rb')
            if options.verbose:
                print "Cache: Loading saved issues data"
            try:
                cachedIssueSet = cPickle.load(fd)
            finally:
                fd.close()

            if cachedIssueSet.cache_version == issueSet.cache_version and \
               cachedIssueSet.head() == issueSet.current_head():
                if options.verbose:
                    print "Cache: It is valid and usable"
                return cachedIssueSet

            if options.verbose:
                print "Cache: No longer valid, throwing it away"

        # We can't use or rely on the cache, so read all details from disk
        issueSet.read_project()
        issueSet.read_issues()

        return issueSet

    load_state = classmethod(load_state)

    def save_state(self):
        """Write an IssueSet to disk in object form, for fast loading on the next
        iteration.  This is only done if there are actual changes to write."""
        if self.dirty:
            for name in self.issues.keys():
                issue = self.issues[name]
                if issue.dirty:
                    if issue.name:
                        self.update_issue(issue)
                    else:
                        self.write_issue(issue)

            cache_file     = self.issues_cache_file()
            cache_file_dir = os.path.dirname(cache_file)

            if not isdir(cache_file_dir):
                os.makedirs(cache_file_dir)

            fd = open(cache_file, 'wb')
            try:
                cPickle.dump(issueSet, fd)
            finally:
                fd.close()

            self.dirty = False

    def __getstate__(self):
        odict = self.__dict__.copy() # copy the dict since we change it
        del odict['dirty']           # remove dirty flag
        return odict

    def __setstate__(self,dict):
        self.__dict__.update(dict)   # update attributes
        self.dirty   = False

######################################################################

# Utility function for calling out to Git (this script does not try to
# be a Git library, just an interface to the underlying commands).  It
# supports a 'restart' keyword, which will cause a Python function to
# be called on failure.  If that function returns True, the same
# command will be attempted again.  This can avoid costly checks to
# make sure a branch exists, for example, by simply failing on the
# first attempt to use it and then allowing the restart function to
# create it.

def git(cmd, *args, **kwargs):
    restart = True
    while restart:
        stdin_mode = None
        if kwargs.has_key('input'):
            stdin_mode = PIPE

        if options.verbose:
            print "Command: git-%s %s" % (cmd, string.join(args, ' '))
            if kwargs.has_key('input'):
                print "Input: <<EOF"
                print kwargs['input'],
                print "EOF"

        proc = Popen(('git-' + cmd,) + args, stdin = stdin_mode,
                     stdout = PIPE, stderr = PIPE)

        if kwargs.has_key('input'):
            proc.stdin.write(kwargs['input'])
            proc.stdin.close()

        returncode = proc.wait()
        restart = False
        if returncode != 0:
            if kwargs.has_key('restart'):
                if kwargs['restart'](cmd, args, kwargs):
                    restart = True
            else:
                if not kwargs.has_key('no_stderr') and proc.stderr:
                    sys.stderr.write(proc.stderr.read())
                raise Exception("Could not complete call: git-%s %s" %
                                (cmd, args))

    if not kwargs.has_key('ignore_output'):
        return proc.stdout.read()[:-1]

class GitIssueSet(IssueSet):
    """This object implements all the command necessary to interact with Git
    for the purpose of storing and distributing issues."""
    def __init__(self):
        self.GIT_DIR    = None
        self.GIT_AUTHOR = None
        IssueSet.__init__(self)

    def git_directory(self):
        if self.GIT_DIR is None:
            self.GIT_DIR = git('rev-parse', '--git-dir')
        return self.GIT_DIR

    def issues_cache_file(self):
        return join(self.git_directory(), "issues")

    def create_issue_branch(self, cmd, args, kwargs):
        """If an issues branch already exists at the remote, we simply refer
        to it from now on.  Otherwise, we create a dummy commit in order get
        things started."""
        try:
            hash = git('rev-parse', 'origin/issues', no_stderr = True)
        except:
            hash = git('hash-object', '-w', '--stdin',
                       input = "Created issues branch\n")
            hash = git('mktree', input = "100644 blob %s\tproject\n" % hash)

            buffer = StringIO()
            self.dump_xml(buffer)
            hash = git('commit-tree', hash, input = buffer.getvalue())
            del buffer

        git('branch', 'issues', hash)
        return True

    def current_head(self):
        return git('rev-parse', 'issues', restart = self.create_issue_branch)

    def current_author(self):
        if self.GIT_AUTHOR is None:
            self.GIT_AUTHOR = Person(git('config', 'user.name'),
                                     git('config', 'user.email'))
        return self.GIT_AUTHOR

    def read_issue(self, name):
        data = git('cat-file', 'blob', '%s/%s/info' % (name[:2], name[2:]),
                   no_stderr = True)
        doc = xml.dom.minidom.parseString(data)
        issue = Issue.from_xml(doc)
        doc.unlink()
        return issue

    def update_issue(self, issue):
        pass

    def write_issue(self, issue):
        """Create a new issue in the tracking database by building a commit
        object that holds a reference to a unique blob describing the issue.
        Its uniqueness is determined by hashing the time of creation, the
        creator's name and e-mail address, and the title of the issues.  The
        issue is then kept under a sub-directory of the same name within the
        issues branch, in a fashion similar to `.git/objects`."""
        assert issue.name is None

        # Create a unique blob to represent the new issue.  This is the
        # issue's official object name from now on, and will never change.
        buffer = StringIO()
        issue.dump_xml(buffer)
        blob = git('hash-object', '-w', '--stdin', input = buffer.getvalue())
        del buffer
        issue.name = blob

        tree = git('mktree', input = "100644 blob %s\tinfo\n" % blob)

        # Merge this blob with existing issue blobs that share the same
        # first two hash digits
        ls_tree = git('ls-tree', '-r', self.head(), '--', blob[:2])
        ls_tree = re.sub('\t%s/' % blob[:2], '\t', ls_tree)
        if ls_tree: ls_tree += '\n'

        tree = git('mktree', input =
                   (ls_tree + "040000 tree %s\t%s\n" % (tree, blob[2:])))

        # Merge it into the tree of issues overall
        ls_tree = git('ls-tree', self.head())
        ls_tree = re.sub('040000 tree [0-9a-f]{40}\t%s\n' % blob[:2],
                         '', ls_tree)
        if ls_tree: ls_tree += '\n'

        tree = git('mktree', input =
                   (ls_tree + "040000 tree %s\t%s\n" % (tree, blob[:2])))

        # Commit the merged tree (though at this moment it's a dangling commit)
        commit = git('commit-tree', tree, '-p', self.head(),
                     input = issue.title)

        # Update the HEAD of the issues branch to point to the commit we
        # just made.
        git('update-ref', 'refs/heads/issues', commit, self.head())

        # Reset the `issues_HEAD` global variable, then return the object
        # name of the new issue.
        self.update_head(commit)

    def read_issues(self):
        ls_tree = string.split(git('ls-tree', '-r', self.head()), '\n')

        self.issues = {}        # clear any existing data

        for line in ls_tree:
            match = re.match('100644 blob ([0-9a-f]{40})\t(project|([0-9a-f]{2})/([0-9a-f]{38})/info)',
                             line)
            assert match

            if match.group(2) == 'project':
                break

            hash = match.group(1)
            assert hash == match.group(3) + match.group(4)

            self.add_issue(self.read_issue(hash))

        return self.issues

######################################################################

parser = optparse.OptionParser()
parser.add_option("-v", "--verbose",
                  action  = "store_true",
                  dest    = "verbose",
                  default = False,
                  help    = "report activity options.verbosely")

(options, args) = parser.parse_args()

def get_issue(issueSet, id):
    issue = None
    try:
        idx = int(id) - 1
        issue = issueSet.issues[issueSet.issues.keys()[idx]]
    except:
        for name in issueSet.issues.keys():
            if re.match(id, name):
                issue = issueSet.issues[name]
                break

    if not issue:
        raise Exception("There is no issue matching the identifier '%s'.\n" % id)

    return issue

######################################################################

if len(args) == 0:
    print "Show help here."
    sys.exit(1)

command = args[0]
args    = args[1:]

######################################################################

# jww (2008-05-12): Pick the appropriate IssueSet to used based on what we
# find in our environment.

issueSet = IssueSet.load_state(GitIssueSet())

######################################################################

if command == "list":
    print
    print "   #    Id     Title                   State  Date  Assign  Tags"
    print "-------------------------------------------------------------------------------"

    index = 1
    for name in issueSet.issues.keys():
        issue = issueSet.issues[name]

        print "%4d  %s  %-23s %-6s %5s %6s %s" % \
            (index, issue.name[:7], issue.title, issue.status,
             issue.created and issue.created.strftime('%m/%d'),
             str(issue.author)[:6], '')

        index += 1

    print

######################################################################

elif command == "show" or command == "dump":
    if len(args) == 0:
        print "Shows needs an index or Id."

    issue = get_issue(issueSet, args[0])
    if command == "show":
        sys.stdout.write("""
      Title: %s
    Summary: %s

Description: %s

     Author: %s
   Reporter: %s
      Owner: %s
   Assigned: %s
         Cc: %s

       Type: %s
     Status: %s
 Resolution: %s
 Components: %s
    Version: %s
  Milestone: %s
   Severity: %s
   Priority: %s
       Tags: %s
   
    Created: %s
   Modified: %s

""" % (issue.title,
       issue.format_long_text(issue.summary),

       issue.format_long_text(issue.description),

       issue.author,
       issue.format_people_list(issue.reporters),
       issue.format_people_list(issue.owners),
       issue.format_people_list(issue.assigned),
       issue.format_people_list(issue.carbons),

       issue.issue_type,
       issue.status,
       issue.resolution or "",
       issue.components or "",
       issue.version or "",
       issue.milestone or "",
       issue.severity,
       issue.priority,
       issue.tags or "",

       issue.created,
       issue.modified))
    else:
        issue.dump_xml()

######################################################################

elif command == "change":
    if len(args) == 0:
        print "Change needs an issue."

    issue = get_issue(issueSet, args[0])

    # jww (2008-05-13): Need to parse datetime, lists, and people
    eval ("issue.set_%s(\"%s\")" % (args[1], args[2]))

######################################################################

elif command == "new":
    if len(args) == 0:
        print "New needs a title."

    issue = Issue(issueSet, issueSet.current_author(), args[0])
    issueSet.add_issue(issue)

######################################################################

# If any of the commands made the issueSet dirty, (possibly) update the
# repository and write out a new cache

issueSet.save_state()

######################################################################

sys.exit(0)

# git-issue ends here
